name: Lighthouse CI
on: deployment
jobs:
  GetUrl:
    runs-on: ubuntu-latest
    steps:
      - name: Get deployment URL
        id: deployment
        uses: dorshinar/get-deployment-url@master
        timeout-minutes: 5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run end-to-end tests
        run: npm run test:e2e
        env:
          deployment: ${{ steps.deployment.outputs.deployment }}
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: ${{ steps.deployment.outputs.deployment }}
          uploadArtifacts: true 
